### ISSUE TITLE
[Bug]: 无法进入/bangumis页面

### ISSUE THREAD

**Issue by morninggrow** [mmdjiji/hexo-bangumis#13]
### 问题描述及如何重现此问题

如题，使用hexo-template搭建博客并且使用使用cactus主题后，浏览器进入域名/bangmis后，浏览器会直接将网页的代码下载，并不会进入预期页面。进入域名/bangumis/会提示"Cannot GET /bangumis/"

### 报错信息（建议使用截图，请尽量截取全部把错误信息）

Cannot GET /bangumis/

### 插件版本

1.0.7

### 环境信息（使用 hexo -v 命令查看）

```shell
9.6.7
```

**Comment by yokinosunsun** [comment]
遇到相同情况了，请问是如何解决的
