### ISSUE TITLE
[Bug]:  TypeError

### ISSUE THREAD

**Issue by reinshift** [mmdjiji/hexo-bangumis#17]
### 问题描述及如何重现此问题

按照readme来的，hexo bangumis -u的时候报错，我是小白不知道怎么解决qwq，问gpt说是在 get-bgm-data.js 文件中的 _createForOfIteratorHelper 函数中，尝试迭代一个非可迭代对象。这可能是因为传递给该函数的参数不符合预期，或者在代码的其他地方出现了问题

### 报错信息（建议使用截图，请尽量截取全部把错误信息）

<img width="706" alt="屏幕截图 2023-12-10 151955" src="https://github.com/mmdjiji/hexo-bangumis/assets/87841481/8b23ecdb-f8ae-4559-84ce-8129d0abaeee">

### 插件版本

1.0.7

### 环境信息（使用 hexo -v 命令查看）

```shell
hexo: 6.3.0
hexo-cli: 4.3.0
os: win32 10.0.22621
node: 18.16.0
acorn: 8.8.2
ada: 1.0.4
ares: 1.19.0
brotli: 1.0.9
cldr: 42.0
icu: 72.1
llhttp: 6.0.10
modules: 108
napi: 8
nghttp2: 1.52.0
nghttp3: 0.7.0
ngtcp2: 0.8.1
openssl: 3.0.8+quic
simdutf: 3.2.2
tz: 2022g
undici: 5.21.0
unicode: 15.0
uv: 1.44.2
uvwasi: 0.0.15
v8: 10.2.154.26-node.26
zlib: 1.2.13
```

**Comment by mmdjiji** [comment]
在 [1.0.9](https://github.com/mmdjiji/hexo-bangumis/releases/tag/1.0.9) 中已解决 TypeError 的问题，如果还是不行请提供下 bangumi 的UID。
